from enum import Enum


class ReasonCode(str, Enum):
    ORDER_UNPAID = "ORDER_UNPAID"
    GROUP_IN_PROGRESS = "GROUP_IN_PROGRESS"
    GROUP_FULL_BUT_AWAITING_PAYMENT = "GROUP_FULL_BUT_AWAITING_PAYMENT"
    GROUP_COMPLETED = "GROUP_COMPLETED"
    GROUP_FAILED = "GROUP_FAILED"
    ORDER_REFUNDED = "ORDER_REFUNDED"
    NOTIFY_PENDING = "NOTIFY_PENDING"
    NOTIFY_RETRY = "NOTIFY_RETRY"
    NOTIFY_FAILED = "NOTIFY_FAILED"
    ORDER_NOT_FOUND_OR_NOT_AUTHORIZED = "ORDER_NOT_FOUND_OR_NOT_AUTHORIZED"
    UNKNOWN_DIAGNOSIS = "UNKNOWN_DIAGNOSIS"
